const BROADCAST_TOPIC = 'broadcast';
const BROADCAST_EVENT_DELETE = 'BROADCAST_EVENT_DELETE';
const BROADCAST_EVENT_NUKE = 'BROADCAST_EVENT_NUKE';
const BROADCAST_EVENT_UPDATE_PUBLISHED_VERSION = 'BROADCAST_EVENT_UPDATE_PUBLISHED_VERSION';

module.exports = {
  BROADCAST_TOPIC,
  BROADCAST_EVENT_DELETE,
  BROADCAST_EVENT_NUKE,
  BROADCAST_EVENT_UPDATE_PUBLISHED_VERSION,
}
