version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    command: npm run start:api:development
    depends_on:
      - mongo
      - redis
    ports:
      - "5001:5001"
    environment:
      - AUTH_TOKEN_SECRET=270336f7f365e82bc9fd4b6f3a0ddeda80e4e576637b81432698ae9e4c3100d2
      - DOMAIN=localhost
      - FRONTEND_URL=https://localhost:5000
      - FILES_DOMAIN=https://files-dev.getleftfield.com
      - MONGODB_URL=mongodb://admin:secret@mongo:27017
      - NODE_ENV=development
      - PORT=5001
      - REDIS_URL=redis://redis
    volumes:
      - ./api:/usr/src/code/api:cached

  workers:
    build:
      context: .
      dockerfile: api.dockerfile
    command: npm run start:workers:build:development
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URL=mongodb://admin:secret@mongo:27017
      - NODE_ENV=development
      - REDIS_URL=redis://redis
    volumes:
      - ./api:/usr/src/code/api:cached

  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    logging:
        driver: none

  redis:
    image: redis:4
    expose:
      - 6379
    logging:
        driver: none
