version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: ./dockerfiles/api.local.dockerfile
    depends_on:
      - mongo
      - redis
    ports:
      - "5001:5001"
    environment:
      - API_DOMAIN=localhost:5001
      - AUTH_TOKEN_SECRET=270336f7f365e82bc9fd4b6f3a0ddeda80e4e576637b81432698ae9e4c3100d2
      - BROADCAST_URL=mqtt://mqtt:1883
      - DOMAIN=localhost:5000
      - EDGE_DOMAIN=localhost:5004
      - EDGE_IP_ADDRESSES=52.223.50.25,35.71.169.90
      - MONGODB_URL=mongodb://admin:secret@mongo:27017
      - NODE_ENV=development
      - PORT=5001
      - REDIS_URL=redis://redis
    volumes:
      - ./api:/usr/src/code/api:cached

  edge:
    build:
      context: .
      dockerfile: ./dockerfiles/edge.local.dockerfile
    depends_on:
      - redis
    ports:
      - "5003:5003"
      - "5004:5004"
    environment:
      - BROADCAST_URL=mqtt://mqtt:1883
      - DEFAULT_MAX_AGE=86400
      - DNS_ZONE=localhost:5004
      - EDGE_DOMAIN=localhost:5004
      - NODE_ENV=development
      - HTTP_PORT=5003
      - HTTPS_PORT=5004
      - REDIS_CACHE_URL=redis://redis
      - REDIS_EDGE_URL=redis://redis
      - REGION=us-east-1
      - SSL_AT_REST_KEY=252216bd27cfaecf0109a9cdc75bf5fc
    volumes:
      - ./edge:/usr/src/code/edge:cached

  task_manufacture:
    build:
      context: .
      dockerfile: ./dockerfiles/task.manufacture.local.dockerfile
    depends_on:
      - mongo
      - redis
    environment:
      - BROADCAST_URL=mqtt://mqtt:1883
      - MONGODB_URL=mongodb://admin:secret@mongo:27017
      - NODE_ENV=development
      - REDIS_URL=redis://redis
    volumes:
      - ./api:/usr/src/code/api:cached
      - ./baseballs:/usr/src/code/baseballs:cached

  task_ssl:
    build:
      context: .
      dockerfile: ./dockerfiles/task.ssl.local.dockerfile
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URL=mongodb://admin:secret@mongo:27017
      - NODE_ENV=development
      - REDIS_URL=redis://redis
      - SSL_AT_REST_KEY=252216bd27cfaecf0109a9cdc75bf5fc
    volumes:
      - ./api:/usr/src/code/api:cached

  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    logging:
        driver: none

  redis:
    image: redis:4
    ports:
      - "6379:6379"
    logging:
        driver: none

  mqtt:
    image: eclipse-mosquitto:latest
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - "1883:1883"
    logging:
        driver: none
