[build]
publish = "www/"
command = "npm run build:local-development"
environment = { AWS_LAMBDA_JS_RUNTIME = "nodejs14.x" }

[functions]
directory = "functions/"

[dev]
publish = "www/"
command = "npm start"
environment = { AWS_LAMBDA_JS_RUNTIME = "nodejs14.x" }
port = 5000
autoLaunch = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Powered-By = "Leftfield"
