/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<ellipse cx="7" cy="7" rx="3" ry="3" transform="rotate(90 7 7)" stroke={color} strokeWidth="2" strokeLinecap="round"/>
<path d="M9.5 5H18C19.1046 5 20 5.89543 20 7V7C20 8.10457 19.1046 9 18 9H9.5" stroke={color} strokeWidth="2" strokeLinecap="round"/>
<ellipse rx="3" ry="3" transform="matrix(4.37114e-08 1 1 -4.37114e-08 17 17)" stroke={color} strokeWidth="2" strokeLinecap="round"/>
<path d="M14.5 15H6C4.89543 15 4 15.8954 4 17V17C4 18.1046 4.89543 19 6 19H14.5" stroke={color} strokeWidth="2" strokeLinecap="round"/>
</svg>
  );
}

export default withTheme(Icon);
