/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<rect x="6" y="3" width="12" height="16" rx="6" stroke={color} strokeLinejoin="round"/>
<path d="M12 22V19" stroke={color} strokeLinecap="round" strokeLinejoin="round"/>
<path d="M10 13H7" stroke={color} strokeLinecap="round" strokeLinejoin="round"/>
<path d="M18 13H16" stroke={color} strokeLinecap="round" strokeLinejoin="round"/>
<path d="M10 9H7" stroke={color} strokeLinecap="round" strokeLinejoin="round"/>
<path d="M18 9H16" stroke={color} strokeLinecap="round" strokeLinejoin="round"/>
</svg>
  );
}

export default withTheme(Icon);
