/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M2 10H14V6.43484C14 6.26397 14.2004 6.17179 14.3302 6.28299L21 12L14.3302 17.717C14.2004 17.8282 14 17.736 14 17.5652V14H2" stroke={color} strokeWidth="2"/>
</svg>
  );
}

export default withTheme(Icon);
