/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="12" cy="12" r="9" stroke={color}/>
<path d="M12 15L12 9" stroke={color} stroke-linecap="square"/>
<path d="M15 12L9 12" stroke={color} stroke-linecap="square"/>
</svg>
  );
}

export default withTheme(Icon);
