/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M13.1818 3.50647L18.3939 5.74025C18.7616 5.89783 19 6.25937 19 6.65939V11.9123C19 13.85 18.0642 15.6684 16.4874 16.7947L13.1625 19.1697C12.4671 19.6664 11.5329 19.6664 10.8375 19.1697L7.51257 16.7947C5.93579 15.6684 5 13.85 5 11.9123V6.65939C5 6.25937 5.2384 5.89783 5.60608 5.74025L10.8182 3.50647C11.5729 3.18305 12.4271 3.18305 13.1818 3.50647Z" fill={color}/>
</svg>
  );
}

export default withTheme(Icon);
