/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<rect x="4" y="4" width="6" height="7" rx="1" stroke={color} stroke-width="2" stroke-linejoin="round"/>
<rect x="4" y="15" width="6" height="5" rx="1" stroke={color} stroke-width="2" stroke-linejoin="round"/>
<rect x="14" y="4" width="6" height="5" rx="1" stroke={color} stroke-width="2" stroke-linejoin="round"/>
<rect x="14" y="13" width="6" height="7" rx="1" stroke={color} stroke-width="2" stroke-linejoin="round"/>
</svg>
  );
}

export default withTheme(Icon);
