/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M12 13L11.6464 13.3536L12 13.7071L12.3536 13.3536L12 13ZM5.64645 7.35355L11.6464 13.3536L12.3536 12.6464L6.35355 6.64645L5.64645 7.35355ZM12.3536 13.3536L18.3536 7.35355L17.6464 6.64645L11.6464 12.6464L12.3536 13.3536Z" fill={color}/>
<path d="M17 18L7 18" stroke={color}/>
</svg>
  );
}

export default withTheme(Icon);
