/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M11 12L10.6464 11.6464L10.2929 12L10.6464 12.3536L11 12ZM16.6464 5.64645L10.6464 11.6464L11.3536 12.3536L17.3536 6.35355L16.6464 5.64645ZM10.6464 12.3536L16.6464 18.3536L17.3536 17.6464L11.3536 11.6464L10.6464 12.3536Z" fill={color}/>
<path d="M6 7V17" stroke={color}/>
</svg>
  );
}

export default withTheme(Icon);
