/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M5 12L5 4" stroke={color} stroke-width="2" stroke-linecap="round"/>
<path d="M19 20L19 18" stroke={color} stroke-width="2" stroke-linecap="round"/>
<path d="M5 20L5 16" stroke={color} stroke-width="2" stroke-linecap="round"/>
<path d="M19 12L19 4" stroke={color} stroke-width="2" stroke-linecap="round"/>
<path d="M12 7L12 4" stroke={color} stroke-width="2" stroke-linecap="round"/>
<path d="M12 20L12 12" stroke={color} stroke-width="2" stroke-linecap="round"/>
<circle cx="5" cy="14" r="2" stroke={color} stroke-width="2" stroke-linecap="round"/>
<circle cx="12" cy="9" r="2" stroke={color} stroke-width="2" stroke-linecap="round"/>
<circle cx="19" cy="15" r="2" stroke={color} stroke-width="2" stroke-linecap="round"/>
</svg>
  );
}

export default withTheme(Icon);
