/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M3 7L10 3L21 7M3 7V12L14 16L21 12V7M3 7L14 11L21 7" stroke={color} strokeWidth="2" strokeLinejoin="round"/>
<path d="M3 12V17L14 21L21 17V12" stroke={color} strokeWidth="2" strokeLinejoin="round"/>
</svg>
  );
}

export default withTheme(Icon);
