/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M10 17L9.64645 16.6464L9.29289 17L9.64645 17.3536L10 17ZM13.6464 12.6464L9.64645 16.6464L10.3536 17.3536L14.3536 13.3536L13.6464 12.6464ZM9.64645 17.3536L13.6464 21.3536L14.3536 20.6464L10.3536 16.6464L9.64645 17.3536Z" fill={color}/>
<path d="M5.93782 13.5C5.14475 12.1264 4.84171 10.5241 5.07833 8.95573C5.31495 7.38734 6.07722 5.94581 7.24024 4.86729C8.40327 3.78877 9.8981 3.13721 11.4798 3.01935C13.0616 2.90149 14.6365 3.32432 15.9465 4.21856C17.2565 5.1128 18.224 6.42544 18.6905 7.94144C19.1569 9.45744 19.0947 11.0869 18.5139 12.5629C17.9332 14.0389 16.8684 15.2739 15.494 16.0656C14.1196 16.8573 12.517 17.1588 10.9489 16.9206" stroke={color} strokeLinecap="round"/>
</svg>
  );
}

export default withTheme(Icon);
