/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M5 8H13" stroke={color} stroke-linecap="round"/>
<path d="M5 12H11" stroke={color} stroke-linecap="round"/>
<path d="M5 16H9" stroke={color} stroke-linecap="round"/>
<path d="M19 18L22 15M19 18L16 15M19 18L19 6" stroke={color}/>
</svg>
  );
}

export default withTheme(Icon);
