/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="12" cy="12" r="3" stroke={color} stroke-width="2"/>
<path d="M12 5V3" stroke={color} stroke-width="2" stroke-linecap="round"/>
<path d="M12 21V19" stroke={color} stroke-width="2" stroke-linecap="round"/>
<path d="M16.9497 7.05026L18.364 5.63605" stroke={color} stroke-width="2" stroke-linecap="round"/>
<path d="M5.63602 18.364L7.05023 16.9497" stroke={color} stroke-width="2" stroke-linecap="round"/>
<path d="M19 12L21 12" stroke={color} stroke-width="2" stroke-linecap="round"/>
<path d="M3 12L5 12" stroke={color} stroke-width="2" stroke-linecap="round"/>
<path d="M16.9497 16.9497L18.364 18.364" stroke={color} stroke-width="2" stroke-linecap="round"/>
<path d="M5.63602 5.63605L7.05023 7.05026" stroke={color} stroke-width="2" stroke-linecap="round"/>
</svg>
  );
}

export default withTheme(Icon);
