/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="12" cy="12" r="7" stroke={color}/>
<circle cx="12" cy="12" r="2" fill={color} stroke={color}/>
<path d="M7.05025 7.05025L4.00005 4.00029M16.9497 7.05025L20 4.00029M20 20.0003L16.9497 16.9497M4.00005 20.0003L7.05025 16.9497" stroke={color} stroke-linecap="round"/>
</svg>
  );
}

export default withTheme(Icon);
