/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="12" cy="12" r="9.5" stroke={color} strokeLinecap="round"/>
<circle cx="9" cy="9" r="1" fill={color} stroke={color} strokeLinecap="round"/>
<circle cx="15" cy="9" r="1" fill={color} stroke={color} strokeLinecap="round"/>
<path d="M15 15.5C15 16.8807 13.6569 18 12 18C10.3431 18 9 16.8807 9 15.5C9 14.1193 10.3431 13 12 13C13.6569 13 15 14.1193 15 15.5Z" fill={color}/>
</svg>
  );
}

export default withTheme(Icon);
