export const ACTBLUE_TRAIT = 'ACTBLUE_TRAIT';

export const CONTENT_TRAIT = 'CONTENT_TRAIT';

export const DONATE_FORM_TRAIT = 'DONATE_FORM_TRAIT';

export const DONATE_BUTTON_TRAIT = 'DONATE_BUTTON_TRAIT';

export const FUNDRAISING_TRAIT = 'FUNDRAISING_TRAIT';

export const OPEN_GRID_TRAIT = 'OPEN_GRID_TRAIT';

export const SECTION_TRAIT = 'SECTION_TRAIT';
