/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M12.6298 3H6.35359C6.1326 3 6 3.13935 6 3.37159V19.6284C6 19.8607 6.1326 20 6.35359 20H12.7403C16.3867 20 18 18.0027 18 15.1694V14.9604C18 12.9399 16.9392 11.4536 15.2597 11.1052C16.674 10.5246 17.4917 9.22404 17.4917 7.59836V7.38934C17.4917 4.71858 15.8564 3 12.6298 3ZM12.0994 6.39071C13.3149 6.39071 13.8453 7.06421 13.8453 7.90027V8.03962C13.8453 8.87568 13.3149 9.59563 12.0994 9.59563H9.73481V6.39071H12.0994ZM12.3204 13.0096C13.4696 13.0096 14.2652 13.5669 14.2652 14.7049V14.9604C14.2652 16.0519 13.4696 16.6093 12.3204 16.6093H9.73481V13.0096H12.3204Z" fill={color}/>
</svg>
  );
}

export default withTheme(Icon);
