/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="12" cy="12" r="7" stroke={color} strokeWidth="2"/>
<circle cx="12" cy="12" r="2" fill={color} stroke={color} strokeWidth="2"/>
<path d="M12 5V3" stroke={color} strokeWidth="2" strokeLinecap="round"/>
<path d="M19 12L21 12" stroke={color} strokeWidth="2" strokeLinecap="round"/>
<path d="M12 21L12 19" stroke={color} strokeWidth="2" strokeLinecap="round"/>
<path d="M3 12H5" stroke={color} strokeWidth="2" strokeLinecap="round"/>
</svg>
  );
}

export default withTheme(Icon);
