/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M14.7565 6H12.3459C12.1647 6 12.0559 6.09836 12.0197 6.2623L10.0079 17.7377C9.97163 17.9016 10.0623 18 10.2435 18H12.6541C12.8353 18 12.9441 17.9016 12.9803 17.7377L14.9921 6.2623C15.0284 6.09836 14.9377 6 14.7565 6Z" fill={color}/>
<rect x="10" y="5" width="7" height="2" fill={color}/>
<rect x="8" y="17" width="7" height="2" fill={color}/>
</svg>
  );
}

export default withTheme(Icon);
