/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="12" cy="3" r="2" fill={color}/>
<circle cx="12" cy="3" r="2" fill={color}/>
<circle cx="12" cy="3" r="2" fill={color}/>
<circle cx="12" cy="3" r="2" fill={color}/>
<circle cx="5" cy="5" r="2" fill={color}/>
<circle cx="5" cy="5" r="2" fill={color}/>
<circle cx="5" cy="5" r="2" fill={color}/>
<circle cx="5" cy="5" r="2" fill={color}/>
<circle cx="19" cy="5" r="2" fill={color}/>
<circle cx="19" cy="5" r="2" fill={color}/>
<circle cx="19" cy="5" r="2" fill={color}/>
<circle cx="19" cy="5" r="2" fill={color}/>
<circle cx="21" cy="12" r="2" fill={color}/>
<circle cx="21" cy="12" r="2" fill={color}/>
<circle cx="21" cy="12" r="2" fill={color}/>
<circle cx="21" cy="12" r="2" fill={color}/>
<circle cx="3" cy="12" r="2" fill={color}/>
<circle cx="3" cy="12" r="2" fill={color}/>
<circle cx="3" cy="12" r="2" fill={color}/>
<circle cx="3" cy="12" r="2" fill={color}/>
<circle cx="5" cy="19" r="2" fill={color}/>
<circle cx="5" cy="19" r="2" fill={color}/>
<circle cx="5" cy="19" r="2" fill={color}/>
<circle cx="5" cy="19" r="2" fill={color}/>
<circle cx="12" cy="21" r="2" fill={color}/>
<circle cx="12" cy="21" r="2" fill={color}/>
<circle cx="12" cy="21" r="2" fill={color}/>
<circle cx="12" cy="21" r="2" fill={color}/>
</svg>
  );
}

export default withTheme(Icon);
