/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="12" cy="12" r="4" stroke={color} strokeWidth="2"/>
<path d="M12 8V4" stroke={color} strokeWidth="2"/>
<path d="M12 20V16" stroke={color} strokeWidth="2"/>
<path d="M9.17157 9.17157L6.34314 6.34314" stroke={color} strokeWidth="2"/>
<path d="M17.6569 17.6569L14.8284 14.8284" stroke={color} strokeWidth="2"/>
<path d="M16 12L20 12" stroke={color} strokeWidth="2"/>
<path d="M4 12L8 12" stroke={color} strokeWidth="2"/>
<path d="M14.8284 9.17157L17.6569 6.34314" stroke={color} strokeWidth="2"/>
<path d="M6.34314 17.6569L9.17157 14.8284" stroke={color} strokeWidth="2"/>
</svg>
  );
}

export default withTheme(Icon);
