/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M9 19L9 12L5.48284 12C5.30466 12 5.21543 11.7846 5.34142 11.6586L12 5L18.6586 11.6586C18.7846 11.7846 18.6953 12 18.5172 12L15 12L15 19" stroke={color} strokeWidth="2"/>
</svg>
  );
}

export default withTheme(Icon);
