/**
 * @WARNING
 * This code is autogenerated by ${root}/icon-helper/transform.js
 */

import React from 'react';
import { withTheme } from 'styled-components';

function Icon(props) {
  const {
    width = 24,
    height = 24,
    color = props.theme.colors.mono[100],
  } = props;

  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M19 15L12 15L12 18.5172C12 18.6953 11.7846 18.7846 11.6586 18.6586L5 12L11.6586 5.34142C11.7846 5.21543 12 5.30466 12 5.48284L12 9L19 9" stroke={color} strokeWidth="2"/>
</svg>
  );
}

export default withTheme(Icon);
