name: Build Edge container
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'edge/**'
      - 'ssl/**'
      - 'package.json'
      - 'package-lock.json'
jobs:
  build-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: edge/staging
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f dockerfiles/edge.remote.dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
      - name: Download task definition
        run: aws ecs describe-task-definition --task-definition team-us-east-1-task --query taskDefinition > task-definition.json
      - name: Deploy Amazon ECS task
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: team-us-east-1-svc
          cluster: team-us-east-1-cls
          wait-for-service-stability: true
