name: Build Edge container image
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'edge/**'
      - 'ssl/**'
      - 'package.json'
      - 'package-lock.json'
jobs:
  build-staging:
    runs-on: ubuntu-latest
    env:
      GITHUB_SHA: ${{ github.sha }}
      SERVICE_NAME: edge
      PROJECT_ID: ${{ secrets.SHARED_GCP_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.SHARED_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.SHARED_GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - run: gcloud auth configure-docker -q

      - name: Build image
        id: build-image
        run: docker build --build-arg -t us.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA -f dockerfiles/edge.remote.dockerfile .

      - name: Push to registry
        run: docker push us.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
