name: Deploy Static Sites to production
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: false

jobs:
  build-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Static sites
        uses: ./.github/actions/build-push-static
        with:
          aws_access_key_id: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          aws_region: us-east-1
          aws_secret_access_key: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
          edge_cache_key: ${{ secrets.PRODUCTION_EDGE_CACHE_KEY }}
          edge_host: getleftfield.com
          git_ref: ${{ inputs.tag || env.GITHUB_SHA }}
          node_env: production
          s3_bucket: leftfield-production-us-east-1
