name: Deploy Static Sites on merge
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'static/**'
      - 'package.json'
      - 'package-lock.json'
jobs:
  build-product-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Static sites
        uses: ./.github/actions/build-push-static
        with:
          aws_access_key_id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws_region: us-east-1
          aws_secret_access_key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          edge_cache_key: ${{ secrets.STAGING_EDGE_CACHE_KEY }}
          edge_host: staging.getleftfield.com
          git_ref: ${{ env.GITHUB_SHA }}
          node_env: staging
          s3_bucket: leftfield-staging-us-east-1
