name: Generate wildcard certificate
on: workflow_dispatch
jobs:
  generate-wildcard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run ssl:wildcard
        env:
          DNSIMPLE_ACCOUNT_ID: ${{ secrets.DNSIMPLE_ACCOUNT_ID }}
          DNSIMPLE_API_TOKEN: ${{ secrets.DNSIMPLE_API_TOKEN }}
          ENVIRONMENTS: staging
          STAGING_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          STAGING_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          STAGING_SSL_AT_REST_KEY: ${{ secrets.STAGING_SSL_AT_REST_KEY }}
          STAGING_STORAGE_PRIMARY_BUCKET: leftfield-staging-us-east-1
          STORAGE_PRIMARY_ENDPOINT: https://s3.us-east-1.amazonaws.com
          WILDCARD_DOMAIN: getleftfield.com
