export const FILLS_CONTAINER_WIDE = 'FILLS_CONTAINER_WIDE';

export const FITS_CONTENT = 'FITS_CONTENT';

export const FULL_SCREEN_WIDTH = 'FULL_SCREEN_WIDTH';

export const GROWS_VERTICALLY = 'GROWS_VERTICALLY';
